default:
  browser: chrome
  implicit_wait: 5
  explicit_wait: 5

test_env:
  base_url: http://127.0.0.1
  port: 8234
  username: byhy
  password: sdfsdf

logging:
  log_level: INFO
  log_file: test.log